// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7BuECQNyCqLVN7wQgO0xzmi4BD35IReg',
    appId: '1:882920291946:web:1042fe62830a454241d413',
    messagingSenderId: '882920291946',
    projectId: 'smartportal-5c501',
    authDomain: 'smartportal-5c501.firebaseapp.com',
    storageBucket: 'smartportal-5c501.firebasestorage.app',
    measurementId: 'G-HQ2Z7SP2NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDGVJ3HNxpG9ywkWTAHPIFkwKeIWbLk08',
    appId: '1:882920291946:android:d04edc093d66c63541d413',
    messagingSenderId: '882920291946',
    projectId: 'smartportal-5c501',
    storageBucket: 'smartportal-5c501.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6n3DiGfWIwlyyCS_gS2p9YyuqlZFug6E',
    appId: '1:882920291946:ios:0894c2632474729941d413',
    messagingSenderId: '882920291946',
    projectId: 'smartportal-5c501',
    storageBucket: 'smartportal-5c501.firebasestorage.app',
    iosBundleId: 'com.example.smartStudentPortal',
  );
}
